# Generated by Django 5.1 on 2026-07-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_academicsupport_is_banned_lesson_scheduled_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(default='8541380592', max_length=100)),
            ],
            options={
                'verbose_name': 'Bot Configuration',
            },
        ),
    ]
