# Generated by Django 5.1 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_botconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='bot_token',
            field=models.CharField(blank=True, default='8806446478:AAGlP8I-wfrA8qbCpFRafXZ83sur2RKKfV0', max_length=200, null=True),
        ),
    ]
