# Generated by Django 5.1 on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_botconfig_bot_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='student_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
